tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "astyle"
brew "aws-cdk"
brew "awscli"
brew "bat"
brew "cookiecutter"
brew "exa"
brew "ffmpeg"
brew "firefox"
brew "gcc"
brew "git"
brew "go"
brew "hadolint"
brew "heroku/brew/heroku"
brew "highlight"
brew "htop"
brew "httpie"
brew "hugo"
brew "jq"
brew "mitmproxy"
brew "p7zip"
brew "rgbds"
brew "ruby"
brew "sdl2"
brew "shellcheck"
brew "terraform"
brew "vim"
brew "wget"
brew "youtube-dl"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "backblaze"
cask "caffeine"
cask "db-browser-for-sqlite"
cask "docker"
cask "font-jetbrains-mono"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "itsycal"
cask "ngrok"
cask "notion"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "robo-3t"
cask "sameboy"
cask "sketch"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "vlc"

mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Things", id: 904280696
